version: "3.7"

services:
  app:
    container_name: MyApp
#    restart: always        
    build:
      context: ./Docker/app
      
    volumes:
      - ./Application:/var/www/html

    networks:
      # used for the nginx service
      frontend:
        aliases:
          - php

      # used for the mysql service
      backend:


  mysql:
    container_name: MySql
#    restart: always        
    build:
      context: ./Docker/mysql    
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '#theSecretOfRoot!'
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: '#secretPassword!'
      MYSQL_DATABASE: 'test_db'

    networks:
      backend:
        aliases:
          - db    
          - database    


  nginx:
    container_name: Nginx
#    restart: always        
    build: 
      context: ./Docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Application:/var/www/html
    networks:
      - frontend      

  memcache:
    container_name: Memcache
    image: memcached:1.5-alpine
#    restart: always        
    networks:
      frontend:
        aliases:
          - memcacheserver


  mailcatcher:
    image: markus2110/mailcatcher:alpine-3.5
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      frontend:   


volumes:
  db_data:

networks:
  frontend:
  backend: