version: "3.7"

services:

  app:
    environment:
      BUILD_ENV: DEV

  mailcatcher:
    image: markus2110/mailcatcher:alpine-3.5
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      frontend:   
