version: "3.7"

services:

  php:
    image: markus2110/php:7.2-fpm-stretch
#    build: 
#      context:    .
#      dockerfile: Dockerfile
#      target :    PRODUCTION
    
    volumes:
      - ./Application:/var/www/html

    networks:
      frontend:
        aliases:
          - php

      backend:
 
  nginx:
    container_name: Nginx
    build: 
      context: ./Docker/nginx
    ports:
      - "8081:80"
      - "4433:443"
    volumes:
      - ./Application:/var/www/html
    networks:
      - frontend 


  mysql:
    container_name: MySql
#    restart: always        
    build:
      context: ./Docker/mysql    
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '#theSecretOfRoot!'
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: '#secretPassword!'
      MYSQL_DATABASE: 'test_db'

    networks:
      backend:
        aliases:
          - db    
          - database          

  memcache:
    container_name: Memcache
    image: memcached:1.5-alpine
#    restart: always        
    networks:
      frontend:
        aliases:
          - memcacheserver


#   mailcatcher:
#     image: markus2110/mailcatcher:alpine-3.5
#     ports:
#       - 1025:1025
#       - 1080:1080
#     networks:
#       frontend:         

volumes:
  db_data:

networks:
  frontend:
  backend: